linters-settings:
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unconvert
    - unused
    - typecheck
    - prealloc
    - nakedret
    - gochecknoinits
