name: ci-go-tests

on:
  pull_request:
    paths-ignore:
    - '**/**.gitignore'
    - '**/**.md'
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    branches:
    - main

jobs:
  ci-go-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          args: --timeout=10m

      - name: Run Unit Tests
        run: go test -race -v ./...
