name: ci-go-tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**/*.go"
      - "**/go.mod"

permissions:
  contents: read
  actions: write

jobs:
  ci-go-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run Unit Tests
        run: go test -race -v ./...
