name: ci-go-unit-tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**/*.go"
      - "**/go.mod"
      - .github/workflows/*

permissions:
  contents: read
  actions: write

jobs:
  ci-go-tests:
    name: Test ${{ matrix.os }}
    runs-on:
      "${{ matrix.os == 'linux' && 'warp-ubuntu-latest-x64-4x' || matrix.os == 'macos' &&
      'warp-macos-15-arm64-6x'}}"

    strategy:
      fail-fast: false
      matrix:
        os: [linux, macos]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache-dependency-path: go.sum

      - name: Run Unit Tests
        run: go test -race -v ./unit_test/...
